### ISSUE TITLE
Build publish

### ISSUE THREAD

**Issue by AlexanderRex** [fpw/MoveVR#2]
Hello, can you please publish builded version, cause I face a lot of errors during try to build it with VS 2017

Thank you :)

**Comment by fpw** [comment]
Hi, you can find the latest published version of MoveVR here: https://folko.solhost.org/movevr/
And more information here: https://forums.x-plane.org/index.php?/files/file/44809-movevr-move-external-windows-into-x-plane-even-into-vr/
It doesn't include the latest contribution (#1), please reopen the issue in case you need a build including that.
